{% set name = "scqubits" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 28e3ff6575d2788b09d47ff3e349771164cf57fab3c30d425fb7709a81ce9f2f

build:
  number: 1
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.28.5
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cython >=0.28.5
    - scipy >=1.1.0
    - matplotlib-base >=3.0.0
    - qutip >=4.3
    - h5py >=2.7.1
    - tqdm
    - ipywidgets
    - typing_extensions

test:
  imports:
    - scqubits

about:
  home: https://github.com/scqubits/scqubits
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Superconducting qubits in Python


  description: |
    scqubits is an open-source Python library for simulating superconducting qubits. It is meant to give the user a
    convenient way to obtain energy spectra of common superconducting qubits, plot energy levels as a function of
    external parameters, calculate matrix elements etc. The library further provides an interface to QuTiP, making it
    easy to work with composite Hilbert spaces consisting of coupled superconducting qubits and harmonic modes.
    Internally, numerics within scqubits is carried out with the help of Numpy and Scipy; plotting capabilities rely
    on Matplotlib.
  doc_url: https://scqubits.readthedocs.io/
  dev_url: https://github.com/scqubits/scqubits

extra:
  recipe-maintainers:
    - jkochNU
    - petergthatsme
