{% set name = "scqubits" %}
{% set version = "4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76351bd6bf4d027762b8977e0758d4c14371df14fdb4cf605baa3b94b64d6348

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy >=1.14.2                         # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
    - numpy
  run:
    - python
    - cycler
    - matplotlib >=3.5.1
    - numpy >=1.14.2
    - qutip >=4.3.1  # [py>=39]
    - scipy >=1.5
    - dill
    - sympy
    - tqdm
    - typing_extensions
    - h5py >=2.10
    - pathos >=0.3.0
    - traitlets
    # Optional dependencies
    - ipywidgets
    - ipyvuetify

test:
  imports:
    - scqubits
  requires:
    - pytest
    - pathos
  commands:
    - pytest --pyargs scqubits

about:
  home: https://github.com/scqubits/scqubits
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Superconducting qubits in Python


  description: |
    scqubits is an open-source Python library for simulating superconducting qubits. It is meant to give the user a
    convenient way to obtain energy spectra of common superconducting qubits, plot energy levels as a function of
    external parameters, calculate matrix elements etc. The library further provides an interface to QuTiP, making it
    easy to work with composite Hilbert spaces consisting of coupled superconducting qubits and harmonic modes.
    Internally, numerics within scqubits is carried out with the help of Numpy and Scipy; plotting capabilities rely
    on Matplotlib.
  doc_url: https://scqubits.readthedocs.io/
  dev_url: https://github.com/scqubits/scqubits

extra:
  recipe-maintainers:
    - jkochNU
    - petergthatsme
